#!/bin/bash
BASE="$(cd `dirname "$0"` && pwd)"

main () {
    local cmd="$1"
    case $cmd in
        'build')
            shift
            build "$@"
            ;;
        'clean')
            shift
            clean "$@"
            ;;
        * )
            echo "
Exiting without running any operations.
Possible operations include:

  build - Install dependencies.
    Usage: ./manage.sh build

  clean - Remove everything generated by this script.
    Usage: ./manage.sh clean
            "
            ;;
    esac
}

build () {
    if ! [ -d "$BASE/node_modules" ]; then
        cd "$BASE/"
        mkdir "$BASE/node_modules"
        npm install "enginemill@0.3.0"
    fi
}

clean () {
    rm -rf "$BASE/node_modules/"
    echo "node_modules/ removed"
}

main "$@"
